openapi: 3.0.0
info: 
  title: Tshit store API
  description: LCO- a course to create API for ecomm store
  version: 1.0.0
  contact:
    email: joelborok@gmail.com
    url: "http://facebook.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: localhost - secure
#   - url: "http://localhost:4000/api/v1"
#     description: localhost - regular 

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: localhost - secure
    variables:
      version:
         enum:
          - v1
          - v2
         default: v1 
      protocol:
        enum:
          - http
          - https    
        default: http
components:
  securitySchemes: 
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer 
paths:
  /:
    get:
      tags:
        - Home
      summary: returns a greet message from lco
      responses:
        200:
          description: All good and successfull
          content: 
            appliction/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:  
          description: internal server error 